/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-dim": "#d8d9e3",
        "on-error": "#ffffff",
        background: "#faf8ff",
        "tertiary-fixed-dim": "#ffb783",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#703700",
        "inverse-surface": "#2e3038",
        "action-blue": "#4583fa",
        "on-surface-variant": "#424654",
        "tertiary-container": "#b55d00",
        "on-secondary-fixed-variant": "#2e3f93",
        "on-secondary-container": "#26378b",
        "on-tertiary-fixed": "#301400",
        surface: "#faf8ff",
        tertiary: "#904900",
        "secondary-fixed-dim": "#bac3ff",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#00429a",
        secondary: "#4758ac",
        "primary-fixed": "#d9e2ff",
        "outline-variant": "#c2c6d6",
        "inverse-primary": "#b0c6ff",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#fffbff",
        "primary-fixed-dim": "#b0c6ff",
        outline: "#727785",
        "on-background": "#191b23",
        "inverse-on-surface": "#eff0fa",
        "surface-container-highest": "#e1e2ec",
        "surface-container": "#ecedf7",
        "on-primary": "#ffffff",
        "on-primary-container": "#fefcff",
        "secondary-fixed": "#dee0ff",
        "surface-container-low": "#f2f3fd",
        "warm-gray": "#f8fafc",
        "surface-variant": "#e1e2ec",
        primary: "#0056c5",
        "on-surface": "#191b23",
        "tertiary-fixed": "#ffdcc5",
        "secondary-container": "#96a5ff",
        "surface-bright": "#faf8ff",
        "surface-tint": "#0058c9",
        "on-error-container": "#93000a",
        error: "#ba1a1a",
        "on-secondary-fixed": "#00115a",
        "surface-container-high": "#e7e7f2",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#2b6fe5",
        "on-primary-fixed": "#001944",
        "trust-navy": "#1e293b",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "section-padding-desktop": "5rem",
        "stack-md": "1rem",
        "section-padding-mobile": "2.5rem",
        gutter: "1.5rem",
        "stack-lg": "2rem",
        "stack-sm": "0.5rem",
        "container-max": "1200px",
      },
      maxWidth: {
        "container-max": "1200px",
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "display-lg-mobile": ["Plus Jakarta Sans"],
        "body-md": ["Inter"],
        "label-md": ["Plus Jakarta Sans"],
        "display-lg": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
      },
      fontSize: {
        "body-lg": ["clamp(1rem, 0.9565rem + 0.2174vw, 1.125rem)", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg-mobile": ["clamp(1.875rem, 1.7446rem + 0.6522vw, 2.25rem)", { lineHeight: "1.2", fontWeight: "700" }],
        "body-md": ["clamp(0.9375rem, 0.8036rem + 0.0419vw, 1.125rem)", { lineHeight: "1.5", fontWeight: "400" }],
        "label-md": ["clamp(0.75rem, 0.7065rem + 0.2174vw, 0.875rem)", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "display-lg": ["clamp(1.75rem, 1.3152rem + 2.1739vw, 3rem)", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-sm": ["clamp(1rem, 0.913rem + 0.4348vw, 1.25rem)", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-md": ["clamp(1.5rem, 1.3261rem + 0.8696vw, 2rem)", { lineHeight: "1.3", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
